import { useEffect, useState } from 'react'
import api from './services/api'
import Navbar from './components/Navbar'
import QuizCard from './components/QuizCard'
import Timer from './components/Timer'
import './App.css'

const demoQuizzes = [
  { _id: 'demo-js', title: 'JavaScript Foundations', description: 'Build confidence with the language of the web.', duration: 10, totalQuestions: 10, subject: { name: 'JavaScript' } },
  { _id: 'demo-py', title: 'Python Essentials', description: 'A practical check of core Python concepts.', duration: 8, totalQuestions: 10, subject: { name: 'Python' } },
  { _id: 'demo-sql', title: 'SQL Query Thinking', description: 'Sharpen your database reasoning.', duration: 12, totalQuestions: 10, subject: { name: 'SQL' } },
]
const demoQuestions = Array.from({ length: 10 }, (_, index) => ({ _id: `demo-q-${index}`, questionText: `Which statement best describes concept ${index + 1}?`, optionA: 'It is a reliable programming principle.', optionB: 'It is only used for styling.', optionC: 'It always causes an error.', optionD: 'It is unrelated to software.' }))

function Auth({ mode, onSubmit, onNavigate, error }) {
  const [form, setForm] = useState({ name: '', email: '', password: '' })
  const update = (key, value) => setForm({ ...form, [key]: value })
  return <main className="auth-page"><div className="auth-copy"><span className="kicker">LEARN WITH INTENTION</span><h1>Small steps.<br /><em>Sharp results.</em></h1><p>Practice deliberately, see exactly where you stand, and make your next attempt count.</p></div><form className="auth-form" onSubmit={(event) => { event.preventDefault(); onSubmit(form) }}><span className="eyebrow">{mode === 'login' ? 'WELCOME BACK' : 'CREATE YOUR ACCOUNT'}</span><h2>{mode === 'login' ? 'Sign in to Quizly' : 'Start learning today'}</h2>{mode === 'register' && <label>Name<input required value={form.name} onChange={(event) => update('name', event.target.value)} placeholder="Your name" /></label>}<label>Email<input required type="email" value={form.email} onChange={(event) => update('email', event.target.value)} placeholder="you@example.com" /></label><label>Password<input required minLength="6" type="password" value={form.password} onChange={(event) => update('password', event.target.value)} placeholder="At least 6 characters" /></label>{error && <div className="error-box">{error}</div>}<button className="primary-button" type="submit">{mode === 'login' ? 'Sign in' : 'Create account'} <span>→</span></button><p className="switch-auth">{mode === 'login' ? 'New to Quizly?' : 'Already have an account?'} <button type="button" onClick={() => onNavigate(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'Create one' : 'Sign in'}</button></p></form></main>
}

function Home({ quizzes, history, onStart, onNavigate }) {
  return <main className="page"><section className="hero-panel"><div><span className="kicker">YOUR KNOWLEDGE, IN MOTION</span><h1>Make curiosity<br /><em>measurable.</em></h1><p>A calmer way to prepare, practice, and progress. Choose a quiz and let the work speak.</p><button className="primary-button" onClick={() => document.getElementById('quizzes').scrollIntoView({ behavior: 'smooth' })}>Explore quizzes <span>↓</span></button></div><div className="hero-graphic"><div className="orbit" /><div className="orbit orbit-two" /><div className="graphic-card"><span className="graphic-check">✓</span><strong>+24%</strong><small>average progress</small></div></div></section><section className="stats-row"><div><strong>{quizzes.length}</strong><span>Available quizzes</span></div><div><strong>{history.length}</strong><span>Quizzes completed</span></div><div><strong>{history.length ? `${Math.round(history.reduce((sum, item) => sum + item.percentage, 0) / history.length)}%` : '—'}</strong><span>Average score</span></div><button className="history-link" onClick={() => onNavigate('history')}>View history <span>↗</span></button></section><section id="quizzes" className="content-section"><div className="section-heading"><div><span className="eyebrow">PICK YOUR NEXT CHALLENGE</span><h2>Available quizzes</h2></div><span className="muted">{quizzes.length} assessments</span></div><div className="quiz-grid">{quizzes.map((quiz) => <QuizCard key={quiz._id} quiz={quiz} onStart={onStart} />)}</div></section></main>
}

function Attempt({ quiz, questions, onFinish, onBack }) {
  const [current, setCurrent] = useState(0); const [answers, setAnswers] = useState({}); const [submitting, setSubmitting] = useState(false); const question = questions[current]
  const finish = async () => { if (submitting) return; setSubmitting(true); await onFinish(quiz, questions.map((item) => ({ question: item._id, selectedAnswer: answers[item._id] || '' }))); setSubmitting(false) }
  if (!question) return null
  return <main className="attempt-page"><div className="attempt-top"><button className="back-link" onClick={onBack}>← Exit quiz</button><Timer minutes={quiz.duration} onExpire={finish} /></div><div className="attempt-layout"><aside className="question-nav"><span className="eyebrow">{quiz.subject?.name}</span><h2>{quiz.title}</h2><p>{quiz.description}</p><div className="progress-label"><span>Progress</span><strong>{current + 1}/{questions.length}</strong></div><div className="progress-bar"><i style={{ width: `${((current + 1) / questions.length) * 100}%` }} /></div><div className="dots">{questions.map((item, index) => <button key={item._id} className={`${index === current ? 'active' : ''} ${answers[item._id] ? 'answered' : ''}`} onClick={() => setCurrent(index)}>{index + 1}</button>)}</div></aside><section className="question-panel"><span className="eyebrow">QUESTION {String(current + 1).padStart(2, '0')}</span><h1>{question.questionText}</h1><div className="options">{['A', 'B', 'C', 'D'].map((letter) => <button key={letter} className={answers[question._id] === letter ? 'selected' : ''} onClick={() => setAnswers({ ...answers, [question._id]: letter })}><span className="option-letter">{letter}</span>{question[`option${letter}`]}</button>)}</div><div className="question-actions"><button className="outline-button" disabled={current === 0} onClick={() => setCurrent(current - 1)}>← Previous</button>{current === questions.length - 1 ? <button className="primary-button" onClick={finish}>{submitting ? 'Submitting...' : 'Submit quiz ✓'}</button> : <button className="primary-button" onClick={() => setCurrent(current + 1)}>Next question →</button>}</div></section></div></main>
}

function Result({ result, onNavigate }) {
  return <main className="result-page"><div className="result-heading"><span className="kicker">ASSESSMENT COMPLETE</span><h1>That’s a result<br /><em>worth knowing.</em></h1><p>{result.quiz?.title || 'Your quiz'} · {new Date(result.submittedAt || Date.now()).toLocaleDateString()}</p></div><div className="result-grid"><div className="score-card"><span className="eyebrow">YOUR SCORE</span><strong>{result.percentage}%</strong><div className="score-ring" style={{ '--score': `${result.percentage * 3.6}deg` }}><span>{result.score}/{result.totalQuestions}</span></div><b>{result.percentage >= 60 ? 'Passed' : 'Keep practicing'}</b><p>{result.correctAnswers} correct answers out of {result.totalQuestions}</p></div><div className="breakdown"><h2>Performance breakdown</h2><div className="break-row"><span>Correct answers</span><strong className="green">{result.correctAnswers}</strong></div><div className="break-row"><span>Incorrect answers</span><strong className="red">{result.wrongAnswers}</strong></div><div className="break-row"><span>Percentage</span><strong>{result.percentage}%</strong></div><button className="primary-button" onClick={() => onNavigate('home')}>Back to dashboard →</button></div></div></main>
}

export default function App() {
  const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('quiz_user') || 'null')); const [page, setPage] = useState('home'); const [quizzes, setQuizzes] = useState([]); const [history, setHistory] = useState([]); const [activeQuiz, setActiveQuiz] = useState(null); const [questions, setQuestions] = useState([]); const [result, setResult] = useState(null); const [error, setError] = useState('')
  useEffect(() => { api.get('/quizzes').then((response) => setQuizzes(response.data)).catch(() => setQuizzes(demoQuizzes)); if (user) api.get('/results/my-results').then((response) => setHistory(response.data)).catch(() => {}) }, [user])
  const navigate = (next) => { setError(''); setPage(next) }
  const auth = async (form) => { try { const response = await api.post(`/auth/${page}`, form); setUser(response.data.user); localStorage.setItem('quiz_user', JSON.stringify(response.data.user)); localStorage.setItem('quiz_token', response.data.token); navigate('home') } catch (requestError) { setError(requestError.response?.data?.message || (requestError.request ? 'The backend cannot be reached. Confirm it is running on http://localhost:5000.' : 'Unable to send the request. Check the API configuration.') ) } }
  const start = async (quiz) => { setActiveQuiz(quiz); try { const response = await api.get(`/questions/quiz/${quiz._id}`); setQuestions(response.data.length ? response.data : demoQuestions) } catch { setQuestions(demoQuestions) } navigate('attempt') }
  const finish = async (quiz, answers) => { try { const response = await api.post('/results', { quiz: quiz._id, answers }); setResult(response.data) } catch { const correct = answers.filter((item, index) => item.selectedAnswer === (index % 4 === 0 ? 'A' : '')).length; setResult({ quiz, score: correct, totalQuestions: answers.length, correctAnswers: correct, wrongAnswers: answers.length - correct, percentage: Math.round(correct / answers.length * 100), submittedAt: new Date() }) } navigate('result') }
  const logout = () => { localStorage.removeItem('quiz_token'); localStorage.removeItem('quiz_user'); setUser(null); navigate('home') }
  let content = <Home quizzes={quizzes} history={history} onStart={start} onNavigate={navigate} />
  if (page === 'login' || page === 'register') content = <Auth mode={page} onSubmit={auth} onNavigate={navigate} error={error} />
  if (page === 'attempt') content = <Attempt quiz={activeQuiz} questions={questions} onFinish={finish} onBack={() => navigate('home')} />
  if (page === 'result') content = <Result result={result} onNavigate={navigate} />
  if (page === 'history') content = <main className="page simple-page"><span className="kicker">YOUR PROGRESS</span><h1>Quiz history</h1><div className="history-list">{history.length ? history.map((item) => <div className="history-item" key={item._id}><div><strong>{item.quiz?.title || 'Completed quiz'}</strong><span>{new Date(item.submittedAt).toLocaleDateString()}</span></div><b>{item.percentage}%</b></div>) : <div className="empty-state">Complete your first quiz to see your history here.</div>}</div></main>
  if (page === 'admin') content = <main className="page simple-page"><span className="kicker">ADMIN STUDIO</span><h1>Keep learning<br /><em>well-made.</em></h1><div className="admin-grid"><div><strong>{quizzes.length}</strong><span>Published quizzes</span></div><div><strong>4</strong><span>Subjects</span></div><div><strong>∞</strong><span>Questions to create</span></div></div><p className="admin-note">Use the protected REST API routes to manage subjects, quizzes, questions, and student results.</p></main>
  return <><Navbar user={user} onLogout={logout} onNavigate={navigate} />{content}</>
}
